### ISSUE TITLE
iteration before '\0'

### ISSUE THREAD

**Issue by casuis** [BatuhanKeskintas/ExamRank02#1]
Hi,

I'm a 42 student in paris who need to pass exam 2.
On your file get_next_line.c, line 40 I can't understand why you put a i++;
You are not the first one I see doing this, but it should put the '\0' one char after needed.

This is my return: 
```
#include        <sys/stat.h>$
$
#include        <fcntl.h> $
$
$
ichar   *get_next_line(int fd)$
{$
a       int             rd;$
n       int             i;$
$
        char    c;$
$
        char    *buffer;$
l$
```
If I'm wrong please explain me why.

**Comment by BatuhanKeskintas** [comment]
Hello,

Thanks for reaching out to me, I did not understand your return clearly and
I did not remember how I implemented on the exam %100 but it is almost the
same as my github code. In my github code "i++"in line 43.

Thank you for paying attention because that is a small mistake. So
basically I changed my code what I did at first right now you can see on
github. In while loop I was increment 'i' after if() so;

we quit from while() when we see '\n' in that case buffer[i] == '\n' and we
are making some error management after the while(). And if everything is
OK, we need to increment i + 1 because we have to put a NULL terminator at
the end of the buffer. If we do not increment you will put it on '\n' which
is not cool :)


But when it comes to your question it is not necessarily that it is my
mistake that I forgot to fix. It does not break anything but if you can
delete it will be more clear code.

I hope this answer is helpful.

Ps: I changed my code as the previous version on github.

Batuhan KESKİNTAŞ

*Electrical - Electronics Engineer*

GSM : +48 739 531 259


asimon ***@***.***>, 12 Şub 2022 Cmt, 15:58 tarihinde şunu
yazdı:

**Comment by casuis** [comment]
I did'nt put a complete return my bad,
But that was the undefined +1 on iteration who mades the first char in 

```
-> ichar   *get_next_line(int fd)$
{$
-> a       int             rd;$
-> n       int             i;$
$
        char    c;$
$
        char    *buffer;$
-> l$
```

And now at your last iteration (EOF) you will also have a +1 char between your last readed char and your '\0' if there is no '\n'.
I used your get_next_line on himself and should return every line of himself.
I think a good way of fixing it would be to iterate in the while and put a '\0' after the error check.

```
	while ((rd = read(fd, &c, 1) > 0))
	{
		buffer[i] = c;
		i++;
		if (c == '\n')
			break;
	}
	if (i = 0 || rd == -1)
	{
		free(buffer);
		return (NULL);
	}
	buffer[i] = '\0';
	return (buffer);
```
Anyway you passed the exam with it so i'm glad to see they don't check for BUFFER_SIZE haha.
And of course thank you for your time.

**Comment by BatuhanKeskintas** [comment]
Hey,

Yes, that is also a possible and shorter solution.  Making increment before
if() is to save your 1 line exactly and improve your quality.

Thanks for reaching out to me, any time I am open to discuss anything :)

Best,

*Batuhan KESKİNTAŞ*

*Electrical - Electronics Engineer*

GSM : +48 739 531 259


asimon ***@***.***>, 12 Şub 2022 Cmt, 17:15 tarihinde şunu
yazdı:
